### ISSUE TITLE
Tracking Iteration 2023-12

### ISSUE THREAD

**Issue by ShiKaiWi** [apache/incubator-horaedb#1333]
## Ease to use
- [x] Avoid the primary key duplicate error when use obkv wal implementation @ShiKaiWi  #1205 (The problem has been fixed in a work around way #1362)
- [ ] Supports idempotence and retry of table creation and deletion. @ZuLiangWang 

### Write
- [ ] Split WAL to OBKV to avoid single large log or log request @ShiKaiWi #1313 
- [ ] Support table migration @chunshao90 

### Query
- [x] Separate the resources used by the queries involving different amount of data @jiacai2050 https://github.com/CeresDB/horaedb/pull/1303
- [ ] Cache the arrow payload in the memory or on the disk instead of the parquet payload to reduce the frequent decoding cost @jiacai2050 @Rachelint 
- [x] Use a read-friendly format for the data in the immutable memtable to reduce the encoding cost during frequent queries @Rachelint 
- [x] Avoid abusing dictionary encoding @ShiKaiWi #1365

## Features
- [x] Support analyze sql for distributed query @baojinri 
- [ ] Support query by opentsdb @baojinri https://github.com/CeresDB/horaedb/pull/1284
