### ISSUE TITLE
Tracking Iteration 2024-01

### ISSUE THREAD

**Issue by ShiKaiWi** [apache/incubator-horaedb#1434]
## Ease to use
- [x] Supports idempotence and retry of table creation and deletion. @ZuLiangWang 
- [ ] #1424 @ZuLiangWang @ShiKaiWi 
- [x] horaecontrol cluster command-line tool @chunshao90 

### Query
- [ ] Cache the arrow payload in the memory or on the disk instead of the parquet payload to reduce the frequent decoding cost @jiacai2050 @Rachelint 
- [ ] Memory cache for object store with new eviction strategy to improve the performance of the query involving large data @Rachelint 
- [ ] Upgrade datafusion, arrow, parquet to latest version @jiacai2050  @tanruixiang 
- [ ] #1441 

## Features
- [x] Preparations for compaction offloading @Rachelint 

## Others
- [x] Merge the `dev` branch into the `main` branch and resolve all the compatibility problems for next version release @ShiKaiWi
