### ISSUE TITLE
Tracking issue for supporting shard level replay

### ISSUE THREAD

**Issue by Rachelint** [apache/incubator-horaedb#412]
### Describe This Problem

Table level replay is too slow, so we try to support shard level replay to relax this problem.
It is a big work, so I split it into some phases and track its progress here. 

### Proposal

- [x] complete unimplemented `scan` method in all wal implementations.
    https://github.com/CeresDB/ceresdb/pull/400
- [ ] implement wal adapter to keep the reading view of table level while using(and the actual reading work is doing in shard level).
    - [ ] implement the read buffer.
    - [ ] implement the wal adapter.
- [ ] refactor the original recovering process to make use of the wal adapter.
    - [ ] refactor the original recovering process in standalone mode.
    - [ ] add `Replayer` to carry out the  recovering work.
- [ ] bug fixs:
    - [ ] recover by `flushed_sequence` in manifest.
    - [ ] modify `RegionId` to a struct including `ShardId` and its version.

**Comment by jiacai2050** [comment]
Fixed in https://github.com/apache/incubator-horaedb/issues/799
