### ISSUE TITLE
Shard based recovery

### ISSUE THREAD

**Issue by Rachelint** [apache/incubator-horaedb#799]
### Describe This Problem

Now table recovery in on table level but wal's storing in on shard level.
The recovery performance may be unsatisfied especially in kafka based wal.  

### Proposal

- Split actual table recovery from schema, and refactor table engine
- Impl shard based table meta recovery
- Impl shard based table data recovery

#### 1. Split actual table recovery from schema, and refactor table engine
We should begin at modifying the high level interface(Schema and TableEngine) for adapting to the new recovery process.

Now the path about `Schema` and `TableEngine` when opening tables on shard is like:
<img src="https://raw.githubusercontent.com/Rachelint/drawio-store/main/now.drawio.svg?sanitize=true">

For modify interfaces above to open whole tables on shard together rather than respectively, the most troublesome place is: 
+ Tables on the same shard may belong to different schema, so we are unable to add the api like `open_tables_on_shard` to `Schema`.

My solution about this is: 
- [x]  Split actual table recovery from schema, we just call the `TableEngine` directly, and just register the opened tables to `Schema` #808 

In this stage, we still keep the origin interface of `TableEngine`, the path may be like:

<img src="https://raw.githubusercontent.com/Rachelint/drawio-store/main/stage1.drawio.svg?sanitize=true">

- [x]  Refactor the `TableEngine` interface to support shard level opening
tbc...
- [ ] Furthermore, split `Schema` and `TableEngine` completely? 

+ Just keep `register_table` and `unregister_table` in `Schema`
+ Remove all table operation(create,drop,open,close), and call them directly in `TableEngine`

#### 2. Impl shard based table meta recovery
- [x] Refactor manifest module
    - Rename the original `TableData` to `TableContext`, and extract members which will be recovered from manifest as the new `TableData`.
    - Register the `TableData` into manifest when `create table` and `open table`, and unregister it when `drop table` and `close table`.
    - When do snapshot in `Manifest`, we just make use of the hold `TableData` rather than scanning the persist wals.
- [x] Place `TableData`s into `Manifest`, and we update the memory and storage in just one place.
- [ ] Shard based manifest recovery

#### 3. Impl shard based table data recovery
- [x] Region based wal replay  #976 
- [ ] Make wal replay more concurrently

#### 4. other
- [x] Add integration test about recovery #996 
- [ ] [WIP] retry when open shard failed
- [ ] Support limited retry in kafka client #1005 
- [ ] Fix logs deleting in wal on kafka

**Comment by ShiKaiWi** [comment]
@Rachelint In the #800, the separate runtime for recovery has been mentioned, and I guess it should be taken into considerations together with this.

**Comment by jiacai2050** [comment]
Most tasks are finished, so closing.
